### ISSUE TITLE
error messages saying object is not exported in namespace file

### ISSUE THREAD

**Issue by sarahollis** [WorldHealthOrganization/godataR#1]
For all of the new functions created, I was able to execute `roxygen2::roxygenise()` to generate the files in `MAN` and `NAMESPACE` files and push this up to main package branch. However, when running from fresh Rstudio start-up I still get these errors... example below

Erreur : 'get_clusters' n’est un object exporté depuis 'namespace:godataR'

But in the end, the collections still load, wondering how to avoid the errors so that it doesn't confuse users.

**Comment by jamesfuller-cdc** [comment]
Are you still getting this error? I can't replicate it on my side. I see that get_clusters.R has the "@export" tag, and the namespace has "export(get_clusters)".

**Comment by jamesfuller-cdc** [comment]
I'm assuming this has been resolved. Can reopen if needed.
