### ISSUE TITLE
Encrypt or protect login credentials

### ISSUE THREAD

**Issue by jamesfuller-cdc** [WorldHealthOrganization/godataR#6]
Encrypt or protect login credentials during the R session. This will prevent passwords from being saved in a user's R scripts. 

Since each function actually makes several API calls, it will be ideal if the user is only prompted for their password once during a session.

The `askpass` or `keyring` packages may work.

**Comment by sarahollis** [comment]
This has been solved via @AmyMikhail's new `getPass` commands so closing out this issue as resolved!
